export const programData = [
    {
        title      : "PAKET A - SPA THERAPIST",
        slug       : "spa-therapist-a",
        category   : "SPA Therapist",
        country    : "Turki",
        countryCode: "tr",
        badgeColor : "bg-red-600",
        description: "Sangat sesuai bagi anda yang ingin bekerja di luar negeri sebagai Spa Therapist, meskipun belum memiliki pengalaman maupun paspor. Seluruh proses disiapkan dari awal hingga siap berangkat.",
        contract   : "8 atau 12 Bulan",
        image      : "/images/program/spa_1.png",

        salaryForeign  : "USD 600 - 700",       
        salaryIdr      : "10.204.200 - 12.755.250",        
        exchangeRate   : "17.007",
        requirements   : [],
        benefits       : ["Sertifikat + Pelatihan", "Mess (Tempat Tinggal)", "Paspor",
                          "Medical Checkup", "KTKLN", "Visa Kerja", "Job 8 atau 12 Bulan (Free Biaya Extend)"],

        gender    : "Pria/Wanita",
        age       : "18 s/d 40 Tahun",
        height    : "Tidak ada persyaratan",
        weight    : "Tidak ada persyaratan",
        language  : "Tidak ada persyaratan",
        education : "Minimal SD (Sekolah Dasar)",
        experience: "Tidak ada persyaratan",
    },
    {
        title      : "PAKET B - SPA THERAPIST",
        slug       : "spa-therapist-b",
        category   : "SPA Therapist",
        country    : "Turki",
        countryCode: "tr",
        badgeColor : "bg-red-600",
        description: "Sangat sesuai bagi anda yang sudah memiliki paspor namun belum memiliki pengalaman, atau sudah berpengalaman tetapi belum memiliki paspor untuk bekerja di luar negeri",
        contract   : "8 atau 12 Bulan",
        image      : "/images/program/spa_2.avif",

        salaryForeign  : "USD 600 - 700",       
        salaryIdr      : "10.204.200 - 12.755.250",         
        exchangeRate   : "17.007",
        requirements   : [],
        benefits       : ["Sertifikat + Pelatihan/Paspor", "Mess (Tempat Tinggal)",
                          "Medical Checkup", "KTKLN", "Visa Kerja", "Job 8 atau 12 Bulan (Free Biaya Extend)"],

        gender    : "Pria/Wanita",
        age       : "18 s/d 40 Tahun",
        height    : "Tidak ada persyaratan",
        weight    : "Tidak ada persyaratan",
        language  : "Tidak ada persyaratan",
        education : "Minimal SD (Sekolah Dasar)",
        experience: "Tidak ada persyaratan",
    },
    {
        title      : "PAKET C - SPA THERAPIST",
        slug       : "spa-therapist-c",
        category   : "SPA Therapist",
        country    : "Turki",
        countryCode: "tr",
        badgeColor : "bg-red-600",
        icon       : "fas fa-spa",
        description: "Dirancang khusus bagi anda yang sudah memiliki pengalaman dan paspor, sehingga dapat langsung melanjutkan proses pemberangkatan kerja ke luar negeri.",
        contract   : "8 atau 12 Bulan",
        image      : "/images/program/spa_3.avif",


        salaryForeign  : "USD 600 - 750",       
        salaryIdr      : "10.204.200 - 12.755.250",         
        exchangeRate   : "17.007",
        requirements   : [],
        benefits   : ["Mess (Tempat Tinggal)", "Medical Checkup", "KTKLN", "Visa Kerja", "Tiket PP", 
                      "Job 8 atau 12 Bulan (Free Biaya Extend)"],

        gender    : "Pria/Wanita",
        age       : "18 s/d 40 Tahun",
        height    : "Tidak ada persyaratan",
        weight    : "Tidak ada persyaratan",
        language  : "Tidak ada persyaratan",
        education : "Minimal SD (Sekolah Dasar)",
        experience: "Tidak ada persyaratan",
    },
    {
        title      : "DUBAI - SPA THERAPIST",
        slug       : "spa-therapist-dubai",
        category   : "SPA Therapist",
        country    : "Dubai",
        countryCode: "ae",
        badgeColor : "bg-red-600",
        icon       : "fas fa-spa",
        description: "Kesempatan berkarier sebagai Spa Therapist di Dubai dengan lingkungan kerja profesional, fasilitas lengkap, dan penghasilan kompetitif.",
        contract   : "2 Tahun",
        image      : "/images/program/dubai_spa.webp",


        salaryForeign  : "AED 2500 - 3000",       
        salaryIdr      : "11.750.000 - 14.250.000",         
        exchangeRate   : "4.750",
        requirements   : [],
        benefits   : ["Mess (Tempat Tinggal)", "Medical Checkup", "KTKLN", "Visa Kerja", "Tiket PP",
                      "Job 8 atau 12 Bulan (Free Biaya Extend)"],

        gender    : "Pria/Wanita",
        age       : "18 s/d 40 Tahun",
        height    : "Tidak ada persyaratan",
        weight    : "Tidak ada persyaratan",
        language  : "English (Intermediate)",
        education : "Minimal SD (Sekolah Dasar)",
        experience: "Tidak ada persyaratan",
    },
    {
        title      : "SPA THERAPIST (COURSE ONLY)",
        slug       : "spa-course-only",
        category   : "SPA Therapist",
        country    : "LKP",
        badgeColor : "bg-red-600",
        icon       : "fas fa-spa",
        description: "Program pelatihan Spa Therapist yang dirancang untuk pemula hingga siap menguasai keterampilan dasar dan teknik profesional di bidang spa.",
        duration   : "1 – 3 Bulan",
        image      : "/images/program/spa_4.avif",
        
        requirements   : [],
        benefits   : ["Pelatihan + Sertifikat"]
    },
    {
        title      : "DUBAI - SPA THERAPIST",
        slug       : "spa-therapist-dubai",
        category   : "SPA Therapist",
        country    : "Dubai",
        countryCode: "ae",
        badgeColor : "bg-red-600",
        icon       : "fas fa-spa",
        description: "Pilihan tepat bagi yang sudah berpengalaman, siap paspor dan ingin segera diproses keberangkatannya",
        contract   : "2 Tahun",
        image      : "/images/program/dubai_spa.webp",


        salaryForeign  : "AED 2500 - 3000",       
        salaryIdr      : "11.750.000 - 14.250.000",         
        exchangeRate   : "4.750",
        requirements   : [],
        benefits   : ["Mess (Tempat Tinggal)", "Medical Checkup", "KTKLN", "Visa Kerja", "Tiket PP", 
                      "Job 8 atau 12 Bulan (Free Biaya Extend)"],

        gender    : "Pria/Wanita",
        age       : "18 s/d 40 Tahun",
        height    : "Tidak ada persyaratan",
        weight    : "Tidak ada persyaratan",
        language  : "English (Intermediate)",
        education : "Minimal SD (Sekolah Dasar)",
        experience: "Tidak ada persyaratan",
    },
    {
        title      : "PAKET A - HOSPITALITY",
        slug       : "hospitality-a",
        category   : "Hospitality",
        country    : "Turki",
        countryCode: "tr",
        badgeColor : "bg-red-600",
        description: "Sangat sesuai bagi Anda yang ingin menjadi Steward, Housekeeping, Laundry Management, ataupun F&B (Waiter/Waitress), namun belum memiliki paspor dan pengalaman. Seluruh proses disiapkan dari awal hingga siap bekerja di luar negeri.",
        contract   : "8 atau 12 Bulan",
        image      : "/images/program/host_1.png",

        salaryForeign  : "USD 600 - 700",       
        salaryIdr      : "10.204.200 - 12.755.250",        
        exchangeRate   : "17.007",
        requirements   : [],
        benefits       : ["Sertifikat + Pelatihan", "Mess (Tempat Tinggal)", "Paspor",
                          "Medical Checkup", "KTKLN", "Visa Kerja", "Job 8 atau 12 Bulan (Free Biaya Extend)"],

        gender    : "Pria/Wanita",
        age       : "18 s/d 40 Tahun",
        height    : "Tidak ada persyaratan",
        weight    : "Tidak ada persyaratan",
        language  : "Tidak ada persyaratan",
        education : "Minimal SD (Sekolah Dasar)",
        experience: "Tidak ada persyaratan",
    },
    {
        title      : "PAKET B - HOSPITALITY",
        slug       : "hospitality-b",
        category   : "Hospitality",
        country    : "Turki",
        countryCode: "tr",
        badgeColor : "bg-red-600",
        description: "Paket B dirancang bagi Anda yang ingin bekerja sebagai Steward, Housekeeping, Laundry Management, ataupun F&B (Waiter/Waitress), serta sudah memiliki paspor namun belum berpengalaman, atau sudah berpengalaman tetapi belum memiliki paspor.",
        contract   : "8 atau 12 Bulan",
        image      : "/images/program/host_2.png",

        salaryForeign  : "USD 600 - 700",       
        salaryIdr      : "10.204.200 - 12.755.250",         
        exchangeRate   : "17.007",
        requirements   : [],
        benefits       : ["Sertifikat + Pelatihan/Paspor", "Mess (Tempat Tinggal)",
                          "Medical Checkup", "KTKLN", "Visa Kerja", "Job 8 atau 12 Bulan (Free Biaya Extend)"],

        gender    : "Pria/Wanita",
        age       : "18 s/d 40 Tahun",
        height    : "Tidak ada persyaratan",
        weight    : "Tidak ada persyaratan",
        language  : "Tidak ada persyaratan",
        education : "Minimal SD (Sekolah Dasar)",
        experience: "Tidak ada persyaratan",
    },
    {
        title      : "PAKET C - HOSPITALITY",
        slug       : "hospitality-b",
        category   : "Hospitality",
        country    : "Turki",
        countryCode: "tr",
        badgeColor : "bg-red-600",
        description: "Pilihan ideal bagi Anda yang ingin berkarier sebagai Steward, Housekeeping, Laundry Management, ataupun F&B (Waiter/Waitress), sudah siap pengalaman dan paspor serta ingin segera diproses keberangkatannya ",
        contract   : "8 atau 12 Bulan",
        image      : "/images/program/host_3.png",

        salaryForeign  : "USD 600 - 700",       
        salaryIdr      : "10.204.200 - 12.755.250",         
        exchangeRate   : "17.007",
        requirements   : [],
        benefits       : ["Sertifikat + Pelatihan/Paspor", "Mess (Tempat Tinggal)",
                          "Medical Checkup", "KTKLN", "Visa Kerja", "Job 8 atau 12 Bulan (Free Biaya Extend)"],

        gender    : "Pria/Wanita",
        age       : "18 s/d 40 Tahun",
        height    : "Tidak ada persyaratan",
        weight    : "Tidak ada persyaratan",
        language  : "Tidak ada persyaratan",
        education : "Minimal SD (Sekolah Dasar)",
        experience: "Tidak ada persyaratan",
    },
    {
        title      : "HOSPITALITY (COURSE ONLY)",
        slug       : "hospitality-only",
        category   : "Hospitality",
        country    : "LKP",
        badgeColor : "bg-red-600",
        icon       : "fas fa-spa",
        description: "Program pelatihan Hospitality yang dirancang untuk mempersiapkan keterampilan kerja di bidang Steward, Housekeeping, Laundry Management, dan F&B (Waiter/Waitress).",
        duration   : "1 – 3 Bulan",
        image      : "/images/program/host_4.png",
        
        requirements   : [],
        benefits   : ["Pelatihan + Sertifikat"]
    },
];